services:
  db:
    image: mysql:8.0
    container_name: online-exam-backend-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: examdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-exam-backend-app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=examdb
      - DB_DIALECT=mysql
    ports:
      - "3000:3000"
    command: ["./start.sh"]
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
